### ISSUE TITLE
iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by C47D** [ppelleti/FeatherWing-template-KiCad#1]
Hi,

Thanks for your template, when trying to load it i got the following error:
![imagen](https://user-images.githubusercontent.com/11037705/66976767-c5f5dc00-f068-11e9-86c0-1537e5f022a6.png)

As I'm new to KiCAD I don't know if it's critical to solve it, is it?

Also had to move the `FeatherWing_KC5` directory out of the generated (by git when clonning) `FeatherWing-template-KiCad` directory to be able to use it, so `FeatherWing_KC5` ends up on my `templates` directory.

**Comment by mignon-p** [comment]
> As I'm new to KiCAD I don't know if it's critical to solve it, is it?

No, not critical at all.  It's just complaining about the color profile in the icon image.  You can just ignore the error.

I don't get this error on my system, but I'll see if I can figure out how to fix it.

**Comment by C47D** [comment]
Did a bit of research and it seems to be an error on libpng, so as you say it isn't critical nor part of the template per se, so I think is fine to close this issue. Thanks for the quick reply :)

**Comment by gabischatz** [comment]
Hi i have the same problem. I have adapted a number of symbols for myself. how can I find out which are the faulty images? 
22:19:47: iCCP: known incorrect sRGB profile
22:19:47: iCCP: known incorrect sRGB profile
22:19:47: iCCP: known incorrect sRGB profile
22:19:47: iCCP: known incorrect sRGB profile

**Comment by mignon-p** [comment]
The image in question (and indeed the only image file in this repo) is [icon.png](https://github.com/ppelleti/FeatherWing-template-KiCad/blob/master/FeatherWing_KC5/meta/icon.png).

This is just a warning about color profiles, so it's completely unimportant.  I'll try to fix the image, though, to avoid the warning.

**Comment by mignon-p** [comment]
Should be fixed now.
