### ISSUE TITLE
Copy to existing project?

### ISSUE THREAD

**Issue by WayneKeenan** [ppelleti/FeatherWing-template-KiCad#2]
Hi, 
I have an existing KiCad (latest v5) project and wondered if you had any tips on copying this into an existing project rather than starting from the template?
Thanks

**Comment by mignon-p** [comment]
I think that adding it to a schematic should be fairly easy.  In EESchema, under the File menu, there's a command "Append Schematic Sheet Content."  I haven't used it myself, but I think this should allow you to merge the schematic from this template into your existing schematic.

For the PCB, I'm less sure how to do it.  Worst case, you could always open up the `.kicad_pcb` files in a text editor and copy and paste between them.  But there might be a better way.

I suggest you ask this question on the [KiCad forum](https://forum.kicad.info/).  Someone more experienced might have a better answer.

**Comment by WayneKeenan** [comment]
"Append Schematic Sheet Content" step went ok, as I was able to copy it from the 'child' sheet into the parent and then delete the 'child'.

For the PCB I did the worst case, copied a subset of the text from your template and hand edited the netlist references in the `.kicad_pcb` file.
